apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ranger-admin
  name: ranger-admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ranger-admin
    spec:
      containers:
      - image: ranger-admin
        name: ranger-admin
        ports:
        - containerPort: 6080
        - containerPort: 6182
        - containerPort: 6083
        - containerPort: 6183
        - containerPort: 8886
        resources: {}
      restartPolicy: Always
status: {}
