apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: test-ingress
    labels:
      app.kubernetes.io/name: {{ include "myapp.name" . }}-ingress
      helm.sh/chart: {{ include "myapp.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    rules:
        - http:
              paths:
                  - path: /ranger
                    backend:
                        serviceName: {{ include "myapp.fullname" . }}-ranger-service
                        servicePort: 6080
